alert('virus!')
alert('virus!')
alert('virus!')
alert('Sabing virus nga eh')
alert('pinindot pa eh')
alert('ay ang kulit talaga!')
alert('balaka nga jan')
alert('-__-')
alert('kulit talaga oh')
alert('hayst')
alert('luh')
alert('dont click') 
alert('masisira buhay mo')
alert('hayst sabi nang--')
alert('balaka jan')
alert('-_-')
alert('........')
alert('^~^')
alert('.....')