alert('GooOod moOoowning')
alert('syempre tatambay ka muna sa higaan mo ng 1 hour niyan bago bumangon')
alert('hope ur day is full of of peace')
alert('osya! bangon na!')
alert('dont forget to eat kung ayaw mong kotongan kita jan')
alert('alam kong tinatamad ka pa')
alert('bangon na!!')
alert('isa...')
alert('dalawa...')
alert('hayst')
alert('ok 10 mins')
alert('ay... 5 mins lang')
alert('-__-')
alert('again, goodmorning, sol!')